### ISSUE TITLE
尝试执行出错

### ISSUE THREAD

**Issue by en0th** [TeraSecTeam/ary#5]
我通过 readme 指定的下载安装更新完毕了，正想测试一番输入了给予的命令
`./ary --vulnscan --engine awvs --url testphp.vulnweb.com -v`

![image](https://user-images.githubusercontent.com/67619247/108054324-7a52a880-7089-11eb-984e-8ee4f87e2608.png)

然而我并不知道发生了什么，难道是参数没有被正确的获取吗？

**Comment by Martin2877** [comment]
您好，`configs/example.setting.ini` 下的 `AWVS_API` 需要修改一下
